apiVersion: v1
kind: Pod
metadata:
  name: green-pod
  labels:
    app: green-pod
spec:
  volumes:
    - name: green-volume
      hostPath:
        path: /home/docker/green-volume
  containers:
    - name: nginx
      image: nginx
      ports:
        - containerPort: 80
      volumeMounts:
        - mountPath: /usr/share/nginx/html
          name: green-volume
    - name: debian
      image: debian
      volumeMounts:
        - mountPath: /host-vol
          name: green-volume
      command: ["/bin/sh", "-c", "echo Green Pod > /host-vol/index.html ; sleep 3600"]
